from typing import Optional
import logging

import numpy as np
from scipy.integrate import simpson

from gwpy.timeseries import TimeSeries
from gwpy.frequencyseries import FrequencySeries
from gwpy.testing.utils import assert_quantity_equal
import astropy.units as u

from .waveform_utils import (
    td_to_fd_waveform, pad_to_get_target_df, restrict_f_range,
    get_signal_at_target_df, get_signal_at_target_frequs
)
from .test_utils import allclose_quantity, assert_allclose_quantity

import gw_signal_tools.cosmo as cosmo


__doc__ = """
Implementation of noise-weighted inner product that is
common in GW data analysis and helpers for computation.
"""


def inner_product(
    signal1: TimeSeries | FrequencySeries,
    signal2: TimeSeries | FrequencySeries,
    psd: Optional[FrequencySeries] = None,
    f_range: Optional[list[float] | list[u.Quantity]] = None,
    df: Optional[float | u.Quantity] = None,
    optimize_time_and_phase: bool = False  # Call it 'compute_match'?
) -> u.Quantity | tuple[TimeSeries, u.Quantity, u.Quantity]:
    r"""
    Calculates the noise-weighted inner product
    .. math:: \langle a, b \rangle = 2 \Re \int_{-\infty}^{\infty}
        \frac{\tilde{a(f) \tilde{b}(f)}{S_n(f)} \, df
    of two signals using their representations
    :math:`\tilde{a}(f), \tilde{b}(f)` in frequency domain.
    
    In case of a `psd` :math:`S_n(f)` that is equal to 1 at all
    frequencies (the default case), this corresponds to the :math:`L^2`
    inner product.

    Parameters
    ----------
    signal1 : ~gwpy.timeseries.TimeSeries or
    ~gwpy.frequencyseries.FrequencySeries
        First signal
    signal2 : ~gwpy.timeseries.TimeSeries or
    ~gwpy.frequencyseries.FrequencySeries
        Second signal
    psd : ~gwpy.frequencyseries.FrequencySeries, optional,
    default = None
        Power spectral density to use in inner product. If None, it is taken
        to be 1 1/Hz at all frequencies.
    f_range : list[float] or list[~astropy.units.Quantity], optional,
    default = None
        Frequency range to compute inner product over. Is potentially
        cropped if bounds are greater than frequency range of one of the
        input signals.

        The whole argument can be None, otherwise it must have length 2.
        However, one of the bounds (or both) can still be None, which
        indicates that no boundary shall be set.
    df : float or ~astropy.units.Quantity, optional, default = None
        Distance df between samples in frequency domain to use in
        integration.
        If None, it is set to 0.0625 Hz (or whatever frequency unit is
        used in the signals), which is the default df of frequency
        domain waveforms generated by `~lalsimulation.gwsignal`.
    optimize_time_and_phase : bool, optional, default = False
        Determines if a match is computed or just a "regular" inner
        product. The match will be optimized over relative time and
        phase shifts between `signal1` and `signal2`.

    Returns
    -------
    ~astropy.units.Quantity or tuple[~gwpy.timeseries.TimeSeries,
    ~astropy.units.Quantity, ~astropy.units.Quantity]
        Inner product value with `signal1`, `signal2` inserted.

    Raises
    ------
    TypeError
        In case either one of `signal1`, `signal2`, `psd` has wrong type.
    ValueError
        In case format of `f_range` parameter is not correct.

    See also
    --------
    gw_signal_tools.waveform_utils.td_to_fd_waveform :
        Used to convert ``TimeSeries`` input to a ``FrequencySeries``.
    gwpy.frequencyseries.frequencyseries.interpolate :
        Function used to get signals to same sampling rate.
    
    Notes
    -----
    Some tips regarding the `df` parameter:
    (i) It should not be too large, otherwise results of the inner
    product may be erroneous.
    (ii) If chosen very small (e.g. in range of 0.001Hz), you should
    consider selecting only powers of two like 2**-10 Hz because these
    work best with certain function calls that utilize the Fourier
    transform of the involved signals. An indicator this might be
    necessary is a shape mismatch error.
    """
    
    # ----- Handling of units -----
    if isinstance(signal1, FrequencySeries):
        frequ_unit = signal1.frequencies.unit
    elif isinstance(signal1, TimeSeries):
        frequ_unit = signal1.times.unit * u.Hz / u.s
    else:
        raise TypeError(
            '`signal2` has to be a GWpy ``TimeSeries`` or ``FrequencySeries``.'
        )

    if isinstance(signal2, FrequencySeries):
        assert frequ_unit == signal2.frequencies.unit, \
            'Need consistent frequency/time units for `signal1` and `signal2`.'
    elif isinstance(signal2, TimeSeries):
        assert frequ_unit == signal2.times.unit * u.Hz / u.s, \
            'Need consistent frequency/time units for `signal1` and `signal2`.'
    else:
        raise TypeError(
            '`signal2` has to be a GWpy ``TimeSeries`` or ``FrequencySeries``.'
        )
    

    # ----- Handling PSD -----
    if psd is None:
        from .PSDs import psd_no_noise

        psd = psd_no_noise.copy()

        # Make sure units are consistent with input. PSD is always a density,
        # i.e. strain per frequency
        psd.override_unit(1 / frequ_unit)  # TODO: change to strain/Hz once lal updates are incorporated
        if (psd_frequ_unit := psd.frequencies.unit) != frequ_unit:
            psd.frequencies *= (frequ_unit / psd_frequ_unit)
    
    if isinstance(psd, FrequencySeries):
        assert frequ_unit == psd.frequencies.unit, \
            'Need consistent frequency/time units for `psd` and other signals.'
        
        assert 1 / frequ_unit == psd.unit, \
            ('Need valid psd units for psd, has to be strain per frequency.')
        # TODO: change to strain/Hz once lal updates are incorporated
    else:
        raise TypeError('`psd` has to be a GWpy ``FrequencySeries`` or None.')


    # ----- Handling df argument -----
    if df is None:
        df = 0.0625 * frequ_unit  # Default value of output of FDWaveform
    else:
        try:
            df = u.Quantity(df, unit=frequ_unit)
        except u.UnitConversionError:
            # Conversion only fails if df is already Quantity and has
            # non-matching unit, so we can assume that df.unit works
            raise ValueError(
                f'Need consistent frequency units for `df` ({df.unit}) and'
                f' signals ({frequ_unit}).'
            )


    # ----- If necessary, do fft (padding to ensure -----
    # ----- sufficient resolution in frequency domain) -----
    if isinstance(signal1, TimeSeries):
        signal1 = td_to_fd_waveform(pad_to_get_target_df(signal1, df))

    if isinstance(signal2, TimeSeries):
        signal2 = td_to_fd_waveform(pad_to_get_target_df(signal2, df))
        

    # ----- Handling frequency range -----
    f_lower, f_upper = [
        max([signal1.frequencies[0], signal2.frequencies[0], psd.frequencies[0]]),
        min([signal1.frequencies[-1], signal2.frequencies[-1], psd.frequencies[-1]])
    ]

    # If bounds are given, check that they fit the input data
    if f_range is not None:
        if len(f_range) != 2:
            raise ValueError(
                '`f_range` must contain lower and upper frequency bounds for'
                'integration. One of them or both can be `None`, but both'
                'have to be specified if `f_range` is given.'
            )
        
        # Check if both lower and upper are given or one of them is None
        if f_range[0] is not None:
            try:
                f_lower_new = u.Quantity(f_range[0], unit=frequ_unit)
            except u.UnitConversionError:
                # Conversion only fails if df is already Quantity and has
                # non-matching unit, so we can assume that df.unit works
                raise ValueError(
                    'Need consistent frequency units for `f_range` members'
                    f' ({f_range[0].unit}) and signals ({frequ_unit}).'
                )
        else:
            f_lower_new = f_lower
        
        if f_range[1] is not None:
            try:
                f_upper_new = u.Quantity(f_range[1], unit=frequ_unit)
            except u.UnitConversionError:
                # Conversion only fails if df is already Quantity and has
                # non-matching unit, so we can assume that df.unit works
                raise ValueError(
                    'Need consistent frequency units for `f_range` members'
                    f' ({f_range[1].unit}) and signals ({frequ_unit}).'
                )

            # TODO: implement check of f_max with Nyquist of signals -> needed?
        else:
            f_upper_new = f_upper


        # New lower bound must be greater than current lower bound,
        # otherwise no values for the range are available in signals
        if f_lower_new >= f_lower:
            f_lower = f_lower_new
        else:
            # Leave lower bound at f_lower, no update
            logging.info(
                f'Given lower bound of {f_lower_new} is smaller than '
                'values available from given signals. Taking a lower '
                f'bound of {f_lower} instead.'
            )

        # New upper bound must be smaller than current upper bound,
        # otherwise no values for the range are available in signals
        if f_upper_new <= f_upper:
            f_upper = f_upper_new
        else:
            # Leave upper bound at f_upper, no update
            logging.info(
                f'Given upper bound of {f_upper_new} is larger than '
                'values available from given signals. Taking an upper '
                f'bound of {f_upper} instead.'
            )

    logging.debug([f_lower, f_upper])


    # ----- Get signals to same frequencies, i.e. make df -----
    # ----- equal (if necessary) and then restrict range -----
    if not optimize_time_and_phase:
        target_range = np.arange(f_lower.value, f_upper.value + 0.9 * df.value, step=df.value) << frequ_unit

        signal1 = get_signal_at_target_frequs(signal1, target_range,
                                              fill_val=0.0 * signal1.unit)
        signal2 = get_signal_at_target_frequs(signal2, target_range,
                                              fill_val=0.0 * signal2.unit)
        psd = get_signal_at_target_frequs(psd, target_range,
                                          fill_val=1.0 * psd.unit)


        return inner_product_computation(signal1, signal2, psd)
    else:
        non_zero_range = [f_lower, f_upper]  # Ensure all signals are non-zero on same range

        if f_lower >= 0.0 * frequ_unit:
            target_range = np.arange(0.0, f_upper.value + 0.9 * df.value, step=df.value) << frequ_unit
        else:
            f_limit = max(abs(f_lower), abs(f_upper))
            target_range = np.arange(-f_limit.value, f_limit.value + 0.9 * df.value, step=df.value) << frequ_unit


        signal1 = get_signal_at_target_frequs(
            signal1,
            target_range,
            fill_val=0.0 * signal1.unit,
            fill_bounds=non_zero_range
        )

        signal2 = get_signal_at_target_frequs(
            signal2,
            target_range,
            fill_val=0.0 * signal2.unit,
            fill_bounds=non_zero_range
        )

        psd = get_signal_at_target_frequs(
            psd,
            target_range,
            fill_val=1.0 * psd.unit,
            fill_bounds=non_zero_range
        )
            

        return optimized_inner_product(signal1, signal2, psd)


def inner_product_computation(
    signal1: FrequencySeries,
    signal2: FrequencySeries,
    psd: FrequencySeries
) -> u.Quantity:
    """
    Lower level function for inner product calculation. Assumes that
    signal conditioning has been done so that they contain values at the
    same frequencies and then carries out the actual computation.

    Parameters
    ----------
    signal1 : ~gwpy.frequencyseries.FrequencySeries
        First signal to put into inner product.
    signal2 : ~gwpy.frequencyseries.FrequencySeries
        Second signal to put into inner product.
    psd : ~gwpy.frequencyseries.FrequencySeries
        Power spectral density to use in inner product.

    Returns
    -------
    ~astropy.units
        Inner product value with `signal1`, `signal2` inserted.
    
    See also
    --------
    scipy.integrate.simpson : Used for evaluation of inner product.
    """

    # ----- Assure same distance of samples -----
    assert (allclose_quantity(signal1.df, psd.df, rtol=0.01)
            and allclose_quantity(signal2.df, psd.df, rtol=0.01)), \
        'Signals must have equal frequency spacing.'
    
    # Second step: make sure frequencies are sufficiently equal.
    # Maximum deviation allowed between the is given df, which
    # determines accuracy the signals have been sampled with.
    custom_error_msg = (
        'Frequency samples of input signals are not equal. This might be '
        'due to `df` being too large. If `df` is already small, consider '
        'choosing a (negative) power of two as these seem to work best.'
    )

    try:
        assert (allclose_quantity(signal1.frequencies, signal2.frequencies,
                                  atol=0.0, rtol=0.01)
                and allclose_quantity(signal1.frequencies, psd.frequencies,
                                      atol=0.0, rtol=0.01)), \
            custom_error_msg
    except ValueError:
        # Due to unequal sample size. Since this is automatically checked by
        # numpy, we can be sure that signal1.size = signal2.size = psd.size
        raise ValueError(custom_error_msg)
    
    output_unit = signal1.unit * signal2.unit / psd.unit * signal1.frequencies.unit
    try:
        output_unit = output_unit.to_system(cosmo)[0]
        # .compose(units=u.astrophys)[0]
    except u.UnitsError:
        output_unit = output_unit.si
        # Resets scale only for units, not for value. Best we can do in that case

    return (4.0 if ((signal1.frequencies[0].value >= 0.0)
                    or (signal1.frequencies[-1].value <= 0.0)) else 2.0  # Check if one-sided or not
            ) * np.real(
        simpson(y=signal1 * signal2.conjugate() / psd, x=signal1.frequencies)
    ) * output_unit


def optimized_inner_product(
    signal1: FrequencySeries,
    signal2: FrequencySeries,
    psd: FrequencySeries,
) -> tuple[TimeSeries, u.Quantity, u.Quantity]:
    """
    Lower level function for inner product calculation. Assumes that
    signal conditioning has been done so that they contain values at the
    same frequencies and then carries out the actual computation.

    In contrast to `inner_product_computation`, this function optimizes
    the inner product over time and phase shifts.

    Parameters
    ----------
    signal1 : ~gwpy.frequencyseries.FrequencySeries
        First signal to put into inner product.
    signal2 : ~gwpy.frequencyseries.FrequencySeries
        Second signal to put into inner product.
    psd : ~gwpy.frequencyseries.FrequencySeries
        Power spectral density to use in inner product.

    Returns
    -------
    tuple[~gwpy.timeseries.TimeSeries, ~astropy.units.Quantity,
    ~astropy.units.Quantity]
        A tuple with three values:
        (i) a ``TimeSeries`` where values of the inner product for
        different relative time shifts between `signal1`, `signal2`
        are stored (optimization over phase is not carried out)
        (ii) maximum absolute value of (i), corresponds to maximization
        of inner product over relative time and phase shifts
        (iii) time at which maximum value (ii) occurs in (i)
    """

    frequ_unit = signal1.frequencies.unit

    # ----- First step: assure same distance of samples -----
    assert (allclose_quantity(signal1.df, psd.df, atol=0.0, rtol=1e-5)
            and allclose_quantity(signal2.df, psd.df, atol=0.0, rtol=1e-5)), \
        'Signals must have equal frequency spacing.'
    
    # ----- Second step: make sure all signals start at valid frequencies -----
    assert ((allclose_quantity(signal1.f0, 0.0 * frequ_unit, atol=0.0, rtol=0.0)
             and allclose_quantity(signal2.f0, 0.0 * frequ_unit, atol=0.0, rtol=0.0)
             and allclose_quantity(psd.f0, 0.0 * frequ_unit, atol=0.0, rtol=0.0))
            or (allclose_quantity(-signal1.f0, signal1.frequencies[-1], atol=signal1.df, rtol=0.0)
                and allclose_quantity(-signal2.f0, signal2.frequencies[-1], atol=signal2.df, rtol=0.0)
                and allclose_quantity(-psd.f0, psd.frequencies[-1], atol=psd.df, rtol=0.0))), \
        ('All signals must start either at f=0 or be symmetric around f=0, '
         'where the latter refers to the case of an odd sample size. For an '
         'even sample size, on the other hand, the number of samples for '
         'positive frequencies is expected to be one less than the number of '
         'samples for negative frequencies, in accordance with the format '
         'expected by `~numpy.fft.fftshift`. Note that the conditions just'
         'mentioned do not apply to the case of a starting frequency f=0, '
         'where both even and odd sample sizes are accepted.')
    

    # ----- Third step: assure frequencies are sufficiently equal. -----
    # ----- Maximum deviation allowed between the is given df, which -----
    # ----- determines accuracy the signals have been sampled with. -----
    custom_error_msg = (
        'Frequency samples of input signals are not equal. This might be '
        'due to `df` being too large. If `df` is already small, consider '
        'choosing a (negative) power of two as these seem to work best.'
    )
    # Is perhaps because interpolate uses fft, which works best with powers of two
    try:
        assert_allclose_quantity(signal1.frequencies, signal2.frequencies,
                                 atol=0.0, rtol=0.01)
        assert_allclose_quantity(signal1.frequencies, psd.frequencies,
                                 atol=0.0, rtol=0.01)
    except ValueError:
        # Due to unequal sample size. Since this is automatically checked by
        # numpy, we can be sure that signal1.size = signal2.size = psd.size
        raise ValueError(custom_error_msg)
    
    # ----- Fourth step: computations -----
    dft_vals = (signal1 * signal2.conjugate() / psd)

    # Append zeros or bring into correct format so that ifft can be used.
    # The prefactor is added here already because it depends on the given
    # frequency range
    if np.isclose(0.0, dft_vals.f0.value, atol=0.0, rtol=0.01):
        full_dft_vals = 4.0 * np.append(dft_vals.value, np.zeros(dft_vals.size - 1))
    else:
        full_dft_vals = 2.0 * np.fft.fftshift(dft_vals.value)

    dt = (1.0 / (full_dft_vals.size * signal1.df)).si

    output_unit = signal1.unit * signal2.unit / psd.unit * signal1.frequencies.unit    
    try:
        output_unit = output_unit.to_system(cosmo)[0]
        # .compose(units=u.astrophys)[0]
    except u.UnitsError:
        output_unit = output_unit.si
        # Resets scale only for units, not for value. Best we can do in that case

    match_series = TimeSeries(
        np.fft.ifft(full_dft_vals / dt.value),  # Discrete -> continuous
        unit=output_unit,
        t0=0.0 * dt.unit,
        dt=dt
    )

    match_result = match_series.abs().max()

    # Handle wrap-around of signal
    number_to_roll = match_series.size // 2  # Arbitrary value, no deep meaning
    match_series = np.roll(match_series, shift=number_to_roll)
    match_series.shift(-match_series.times[number_to_roll])

    # Compute peak time
    peak_index = np.argmax(match_series)
    peak_time = match_series.times[peak_index]
    
    return match_series, match_result, peak_time


def norm(
    signal: TimeSeries | FrequencySeries,
    *args,
    **kwargs
) -> u.Quantity | tuple[TimeSeries, u.Quantity, u.Quantity]:
    """
    Wrapper function for calculation of the norm of the given `signal`
    (i.e. square root of inner product between `signal` and `signal`,
    its SNR) as measured by the noise-weighted inner product
    implemented in `inner_product`.

    Parameters
    ----------
    signal : ~gwpy.timeseries.TimeSeries or
    ~gwpy.frequencyseries.FrequencySeries
        Signal to compute norm for.
    *args, **kwargs
        Additional arguments, will be passed to `inner_product` function.

    Returns
    -------
    ~astropy.units.Quantity or tuple[~gwpy.timeseries.TimeSeries,
    ~astropy.units.Quantity, ~astropy.units.Quantity]
        Norm of `signal`, i.e. square root of inner product of `signal`
        with itself.

        If `optimize_time_and_phase = True`, a tuple is returned that
        contains a ``TimeSeries``, the aforementioned norm and a time.
        See `optimized_inner_product` for details on the return.
    
    See also
    --------
    gw_signal_tools.inner_product.inner_product :
        Arguments are passed to this function for calculations.
    """

    out = inner_product(signal, signal, *args, **kwargs)

    if isinstance(out, u.Quantity):
        return np.sqrt(out)
    else:
        return np.sqrt(out[0]), np.sqrt(out[1]), out[2]


def overlap(
    signal1: TimeSeries | FrequencySeries,
    signal2: TimeSeries | FrequencySeries,
    *args,
    **kwargs
) -> u.Quantity | tuple[TimeSeries, u.Quantity, u.Quantity]:
    """
    Wrapper for calculation of the overlap of two given signals as
    measured by the noise-weighted inner product implemented in
    `inner_product`. This means the signals are normalized to have unit
    norm (with respect to this inner product) and then inserted into
    `inner_product`.

    Parameters
    ----------
    signal1 : ~gwpy.timeseries.TimeSeries or
    ~gwpy.frequencyseries.FrequencySeries
        First signal.
    signal2 : ~gwpy.timeseries.TimeSeries or
    ~gwpy.frequencyseries.FrequencySeries
        Second signal.
    *args, **kwargs
        Additional arguments, will be passed to `inner_product` function.

    Returns
    -------
    ~astropy.units.Quantity or tuple[~gwpy.timeseries.TimeSeries,
    ~astropy.units.Quantity, ~astropy.units.Quantity]
        Overlap of `signal1` and `signal2`.

        If `optimize_time_and_phase = True`, a tuple is returned that
        contains a ``TimeSeries``, the aforementioned norm and a time.
        See `optimized_inner_product` for details on the return.
    
    See also
    --------
    gw_signal_tools.inner_product.inner_product :
        Arguments are passed to this function for calculations.
    """

    out = inner_product(signal1, signal2, *args, **kwargs)

    normalization = 1.0  # Default value

    if isinstance(norm1 := norm(signal1, *args, **kwargs), u.Quantity):
        normalization *= norm1
    else:
        normalization *= norm1[1]

    if isinstance(norm2 := norm(signal2, *args, **kwargs), u.Quantity):
        normalization *= norm2
    else:
        normalization *= norm2[1]


    if isinstance(out, u.Quantity):
        return out / normalization
    else:
        return out[0] / normalization, out[1] / normalization, out[2]
